### PR TITLE
feat: add Setting to disable config interceptor

### LINKED ISSUE #534: Add settings value to disable the configuration interceptor
Due to some issues reported by @thilo20, it should be possible to force the Dataspace Connector to load the `config.json` and set this configuration as active, instead of loading one from the database and ignoring the file on a restart. Therefore, a value named e.g. `configuration.force-reload.enabled=true` could be added to the `application.properties`.

### PR DESCRIPTION
**Pull request by vdakker**
**Bugs fixed so far:**
- [x] ConfigurationService : The IDS-Messaging-Services never actively used the new data for the keystore and truststore when the active configuration was swapped/changed. The called updateConfiguration() works using a KeyStoreManager with old data and replaces the old KeyStoreManager instance with a new instance but re-using the old keystore/truststore data from the old KeyStoreManager. KeyStoreManager needs to be updated at runtime first before calling updateConfiguration(). [Bug here](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/src/main/java/io/dataspaceconnector/service/resource/type/ConfigurationService.java#L145).
- [x] PreConfigInterceptor: When initially loading the configuration from the config.json at startup, the passwords and alias for the KeyStore and Truststore were never saved in the DSC DB. The data is not specified in the config.json, but in the application.properties of the DSC. Until now, only the data from config.json was persisted at startup. You can also see from the linked code that a swap of the active configuration was done afterwards and the Messaging-Services never used the new active config, otherwise they would not have worked without KeyStore and Truststore settings (see first bug). [Bug here](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/c19010f585039245989b6a327c98d3ae27761975/src/main/java/io/dataspaceconnector/config/PreConfigInterceptor.java#L112).

**Enhancements so far:**
- [x] It is now possible to force the reloading of the configuration from the config.json when starting the Connector. The configuration marked as active in the database is ignored when starting the Connector as a result. The data from the config.json and the application.properties (truststore/keystore pw and alias) are then written to the DSC database as new active config and used and can be changed via API. New start of DSC with forcing reload will reload the config from the config.json again. New setting in the application.properties and thus environment variables depending on the setup: `configuration.force.reload=true/false`, true will force reloading config from config.json/application.properties, default if not set is false.
- [x] If a configuration is activated at runtime via DSC APIs that cannot be processed by the Messaging-Services (which then throw a ConfigUpdateException), e.g. because values of the KeyStore or TrustStore settings like `alias` or `password` are `null`, the system rolls back to the old working configuration and sets this as active configuration again in DSC DB and Messaging-Services. Example of the functionality in progress can be seen in new Test in `ConfigurationControllerIT.setConfiguration_invalidConfigInput_rollBack`.

### CODE REVIEW

**Comment by vdakker** [comment]
~~When writing a Configuration from JSON to the DB (using `configurationSvc.create(configDesc);`) and then trying to overwrite it after a restart (using `configurationSvc.update(configuration.get().getId(), configDesc);`), the connector throws a `LazyInitializationException: failed to lazily initialize a collection of role: io.dataspaceconnector.model.configuration.Configuration.additional`.~~

Done

**Comment by vdakker** [comment]
> ~~When writing a Configuration from JSON to the DB (using `configurationSvc.create(configDesc);`) and then trying to overwrite it after a restart (using `configurationSvc.update(configuration.get().getId(), configDesc);`), the connector throws a `LazyInitializationException: failed to lazily initialize a collection of role: io.dataspaceconnector.model.configuration.Configuration.additional`.~~

~~Adding Eager Fetching to Additional in Entity fixes this, but there is still a cyclic depdency, because in `reload` calls `svcResolver.getService(ConfigContainer.class);`, which is trying to get the `ConfigContainer` bean, before it is created by the `ConfigProducer` (which is still in `PostConfigInterceptor` state)~~

Done

**Comment by ghost** [comment]
~~TODO: If it should work, the changelog would have to be updated.~~

Done

**Comment by ghost** [comment]
just noticed: this is PullRequest 600 🥳 🎂 🎉 🎈

**Comment by ghost** [comment]
~~Keep in mind: if someone is sending us null-values for the KeyStore or TrustStore configuration (e.g. password:null) via API or UI/API, these null-values will actually be set in the Dataspace Connector DB and tried to be used following by the Messaging-Services if the null-value-config becomes the active config, will not work (Messaging-Services will print error-log message)~~

DONE (has been addressed by rollback functionality)

**Comment by vdakker** [comment]
> 
> 
> Keep in mind: if someone is sending us null-values for the KeyStore or TrustStore configuration (e.g. password:null) via API or UI/API, these null-values will actually be set in the Dataspace Connector DB and tried to be used following by the Messaging-Services if the null-value-config becomes the active config, will not work (Messaging-Services will print error-log message)
> 
> https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/c19010f585039245989b6a327c98d3ae27761975/src/main/java/io/dataspaceconnector/model/configuration/ConfigurationFactory.java#L279

The DSC will now roll back to the last valid configuration, if someone tries to set an invalid configuration as active. When updating the active configuration to an invalid one, the changes will be ignored. When trying to set another invalid config as active, the current configuration will be kept as the active one.

**Review by juliapampus — DISMISSED** [review]

**Review by juliapampus — APPROVED** [review]

**Pull request merged**
