### PR TITLE
feat: generate accessUrl for app-endpoints at app-deployment

### LINKED ISSUE #556: Generate accessUrl for the app-endpoints at app-deployment
In order for apps and their app-endpoints to be used in routes, the complete individual accessUrl of an app-endpoint must be determined at app-deployment time and saved within the DSC. Dynamic parts are mainly the container-name and the exposed-port, which can change with each app-deployment.

### PR DESCRIPTION
**Pull request by vdakker**
- [x] save Endpoint-accessUrls of AppEndpoints of Apps in AppEndpoint-location
- [x] determine accessUrls/locations of AppEndpoints at every App-start time (uses container-name and exposed port)
- [x] provide AppEndpointImpl to save exposed port for AppEndpoint by Portainer
- [x] provide method to validate if App-to-stop part of active camel-routes
- [x] provide new HTTP->HTTP Camel Template for App -> App

### CODE REVIEW

**Comment by ghost** [comment]
Would like to think through again, because the App-model already contains a `List<AppEndpoint> endpoints`, which can be queried by /api/apps/{id}/endpoints, which then, however, do not represent the data at runtime.

`     "endpointPort": 80,
        "mediaType": "application/json"`

The data specified in the AppImpl for the concrete runtime e.g. exposed ports should then be able to be linked to these.

**Comment by ghost** [comment]
~~Note: RouteConfigurer.getRouteTemplate needs to provide template for AppEndpoints (currently only GenericEndpoint and ConnectorEndpoint)~~

Update: first version of http->http camel template is now available: https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/557/commits/65620ff094c133e3a06eb5948bf32e7840612df4

**Comment by ghost** [comment]
Further changes will take place in PR:
https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/650

**Comment by juliapampus** [comment]
Will be merged with PR #650

**Pull request closed without merging**
