### PR TITLE
feat(database): added ojdbc driver to connect with Oracle, including …

### PR DESCRIPTION
**Pull request by difu**
PR for issue International-Data-Spaces-Association/DataspaceConnector#37 

- Added ojdbc driver
- Example docker-compose
- Updated doc with example usage

### CODE REVIEW

**Comment by brianjahnke** [comment]
Hi,

thank you for raising the feature request and directly implementing it!

Would you please be so kind to clarify the following points:
- Would it possible to combine files and comment out  the alternative configuration? This would bundle all configurations in the same places.
  My suggestion would be: Combine `docker-compose.yaml` and `docker-compose-oracle.yaml` into one file (`docker-compose.yaml`), `connector.env` and `connector-oracle.env` into one file (`connector.env`), as well as `postgres.env` and `oracle.env` (maybe `backend.env`?).
- The oracle image `gvenzl/oracle-xe:21.3.0-slim`  is not an official image. Is there one or is there a good reason to use a third parties image? I am concerned regarding support and supplychain integrity.
- The documentation states `add a persistent volume in the
docker-compose_oracle.yaml`. Would it be possible to show how this is done? This would help people new with docker.
- In the `pom.xml` `ojdbc10` is used as package. I just saw that there is a [`odjbc11`](https://search.maven.org/artifact/com.oracle.database.jdbc/ojdbc11/21.5.0.0/jar) available. Is there a reason to chose the older one? And what is the difference to the `-production` ones?
- [This oracle guide](https://blogs.oracle.com/developers/post/configuring-the-oracle-jdbc-drivers-in-a-springboot-project) states `ucp` is also required as a dependency, but it is not included. Is there a reason for this?

The following is missing:
- The feature is missing e2e tests. The e2e should be extended to start the connector with a oracle database so that the correctness of database queries could be validated. Otherwise consistently verifying the correctness of the implementation will be impossible.

**Comment by difu** [comment]
Hi,

thanks for your feedback!

> • Would it possible to combine files and comment out the alternative configuration? This would bundle all configurations in the same places.
I thought for myself about that. I am not a docker-compose expert. I looked at some possible ways of doing that, for example with profiles. All my solutions ended up adding some kind of switch to toggle wether to use Postgres or Oracle. This would possibly break a simple „docker-compose up“. But let me know if you have a solution! I will also try to figure out.

> • The oracle image gvenzl/oracle-xe:21.3.0-slim is not an official image. Is there one or is there a good reason to use a third parties image? I am concerned regarding support and supplychain integrity.
Gerald Venzl (gvenzl) is an Oracle employee and product manager of XE Editions. There are also some official Docker builds but this is the far most easiest to handle.
According to the License Agreements https://www.oracle.com/downloads/licenses/db18c-express-license.html:
"We grant you a nonexclusive, nontransferable limited license to use the programs for: (a) purposes of developing, prototyping and running your applications for your own internal data processing operations; (b) you may also distribute the programs with your applications; (c) you may use the programs to provide third party demonstrations and training; and d) you may copy and distribute the programs to your licensees provided that each such licensee agrees to the terms of this Agreement. You are not permitted to use the programs for any purpose other than as permitted under this Agreement. Program documentation is either shipped with the programs, or documentation may accessed online at https://docs.oracle.com/en/.“
I am not a lawyer(!!!) but as far as we are just using the image I don’t think there is a problem. 
This repo also use the official binaries.
From a technical point of view this XE Edition provides the same functionality, interface etc. as the big commercial versions. There are only restricted in CPU, memory and storage.
For most versions of Oracle Enterprise versions an XE based image is available so in an automated CI checks against all these versions should be possible.

> • The documentation states add a persistent volume in the docker-compose_oracle.yaml. Would it be possible to show how this is done? This would help people new with docker.
Yes, I could add an example!

> • In the pom.xml ojdbc10 is used as package. I just saw that there is a odjbc11 available. Is there a reason to chose the older one? And what is the difference to the -production ones?
Good point. In my experience ojdbc10 is currently more widely used as it covers latest versions as it covers elder versions of Oracle. There wasn’t really a good reason for not using 11, just expediance.

> • This oracle guide states ucp is also required as a dependency, but it is not included. Is there a reason for this?

I don’t think this is a must have. The UCP allows you to effectively handle large amounts of DB connections. And also some transparent failover scenarios are covered. For small number of connections (whatever that means) I think it is overhead. 
In my very little tests with the connector it works and the connections seemed to be established.
https://docs.oracle.com/en/database/oracle/oracle-database/21/jjucp/intro.html#GUID-82ACD002-4C5F-4BF7-99FF-46A2A97DD35D
On the other hand maybe we could try to add it and test.

> • The feature is missing e2e tests. The e2e should be extended to start the connector with a oracle database so that the correctness of database queries could be validated. Otherwise consistently verifying the correctness of the implementation will be impossible.
Could you give me a hint, where in the repo the instantiation is?
The only difference/addition should be to spin up Oracle as backend. Maybe this part would benefit from your first point.

Hope this helps and let me know!

Cheers from Frankfurt,

Dirk

**Comment by brianjahnke** [comment]
Hi,

thanks for the detailed insights!

> I thought for myself about that. I am not a docker-compose expert. I looked at some possible ways of doing that, for example with profiles. All my solutions ended up adding some kind of switch to toggle wether to use Postgres or Oracle. This would possibly break a simple „docker-compose up“. But let me know if you have a solution! I will also try to figure out.

Maybe with comments? Comment out the config currently not selected. This should be quite straight forward and not confuse new users. Something like [Gitea docs](https://docs.gitea.io/en-us/install-with-docker/#mysql-database)? What do you think?

> I don’t think this is a must have. The UCP allows you to effectively handle large amounts of DB connections. And also some transparent failover scenarios are covered. For small number of connections (whatever that means) I think it is overhead.
In my very little tests with the connector it works and the connections seemed to be established.

Let's see if the tests run without it. There are other solutions for optimizing DB connections and adding a dependency is always easier then removing it. ^^

> Could you give me a hint, where in the repo the instantiation is?

The e2e are started by running this [shell script](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/scripts/ci/e2e/test-provider-consumer.sh) in the [CI pipeline](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/06ae90adf0d788e8812191e8745a6a3d09aecab5/.github/workflows/ci.yml#L389). They spin up the helm chart under `charts\dataspaceconnector` with this [provider configuration](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/06ae90adf0d788e8812191e8745a6a3d09aecab5/scripts/ci/libraries/dsc.sh#L28) and this [consumer configuration](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/06ae90adf0d788e8812191e8745a6a3d09aecab5/scripts/ci/libraries/dsc.sh#L31). The helm chart itself deploys the database (currently postgres).

Without deep diving i think the following changes need to be applied for the oracle e2e tests to be added:
- The oracle dependency would need to be added in the helm chart.
- The appropriate backend configuration needs to be selected when deploying (the spring driver etc. like in the docker-compose.).
- The CI pipeline should spin up a second e2e environment with oracle. In parallel testing should be a faster.

Hope this helps and thank you!

**Comment by difu** [comment]
Hi,
> My suggestion would be: Combine docker-compose.yaml and docker-compose-oracle.yaml into one file (docker-compose.yaml), connector.env and connector-oracle.env into one file (connector.env), as well as postgres.env and oracle.env (maybe backend.env?).
> Maybe with comments? Comment out the config currently not selected. This should be quite straight forward and not confuse new users. Something like [Gitea docs](https://docs.gitea.io/en-us/install-with-docker/#mysql-database)? What do you think?

Not sure about that. Merging `postgres.env` and `oracle.env` is indeed easy, as the environment vars are independent from each other. This could/should be done.
Merging `connector.env` and `connector_oracle.env` forces commenting out either the Postgres or the Oracle part. Personally, I don't like such configuration settings to be under version control. Imagine a user who uses Oracle as backend, this changed file would be in the git changelist, although it has nothing to do with "changes in the code", it is a decision. (Hard to describe, I hope you get my point :-) )
At the moment (this PR) the user as only to choose between using docker-compose.yaml and docker-compose_oracle.yaml. Also a new user has to change/comment/uncomment 2 files (`docker-compose.yaml` and `backend.env)` to choose one of the two backends. At the end it's your decision :-D

> The feature is missing e2e tests. The e2e should be extended to start the connector with a oracle database so that the correctness of database queries could be validated. Otherwise consistently verifying the correctness of the implementation will be impossible.

I took a look at it. Unfortunately I do not have a K8S/Helm environment to implement and test this, so it is rather hard for me to do all the work. But I could assist you?



Cheers, Dirk

**Comment by HeinrichPet** [comment]
As discussed with @difu and @SebastianOpriel, we will close this PR. 

The DSC maintainers have already decided some time ago to stop developing the DSC and to switch to the [Eclipse Project](https://github.com/eclipse-dataspaceconnector). Nevertheless, we don't want to simply drop the good contribution. @SebastianOpriel will open a new PR accordingly, in which he will document the approach of connecting an Oracle database in the DSC documentation.

Thanks a lot for your work @difu.

**Pull request closed without merging**
