### PR TITLE
feat: add ids-certificate expiration date and dat info to actuator/info

### LINKED ISSUE #648: [actuator] Expiration date of certificates
Feature request received:
Is it possible to include the expiration date for the TLS certificate and the connector certificate into the actuator/info API?

Messaging-Services already provide a getCertExpiration() to get the expiration date of the connector certificate.

### PR DESCRIPTION
**Pull request by vdakker**
closes  https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/648

### CODE REVIEW

**Comment by tmberthold** [comment]
image

**Comment by ghost** [comment]
image

**Comment by vdakker** [comment]
Added more information (infomodel versions, dat issuer/expiration) to actuator endpoint.

actuator2

**Comment by juliapampus** [comment]
Just one small comment @vdakker: Could you (if possible) avoid to use the @SuppressFBWarnings annotation? The check aims at finding implementations not following best practices, so we should not just bypass them.

**Comment by vdakker** [comment]
> 
> 
> Just one small comment @vdakker: Could you (if possible) avoid to use the @SuppressFBWarnings annotation? The check aims at finding implementations not following best practices, so we should not just bypass them.

just removed the annotation, was possible in this case

**Comment by vdakker** [comment]
Added securityProfile and referringConnector fields from the DAT claims to the actuator endpoint

actuator3

**Review by juliapampus — DISMISSED** [review]

**Review by juliapampus — APPROVED** [review]

**Pull request merged**
