### PR TITLE
feat: Remote Attestation with CMC and tpm2d support

### PR DESCRIPTION
**Pull request by milux**
PR includes the "new" CMC as well as the "old" tpm2d RA driver.
We may remove the latter, if desired.
The RA method is currently fixed to "CMC", see IDSCP2 server XML.
We should implement a dynamic approach for this, so RA can be changed or disabled, before merge.

### CODE REVIEW

**Comment by juliapampus** [comment]
@brianjahnke was asked to take a look at the Docker image. @milux is waiting for feedback.

**Comment by brianjahnke** [comment]
Hi,
already gave feedback. Waiting for fixes.

**Comment by HeinrichPet** [comment]
- Implementation ready till 9th December
- Tests and FOSS of CMC ready till 16th December

**Comment by HeinrichPet** [comment]
Hi, 

we still need the documentation on how to use RA. Please provide that via /docs/.

Best regards,
Heinrich

**Comment by brianjahnke** [comment]
Hi,
- The Changelog is missing.
- The temporary publishing to local repository needs to be removed.
- The e2e test are failing.
- The changes to the dockerfile seem strange. Would you be so kind to explain why a local copy of the configuration is added as a single layer?

**Comment by milux** [comment]
> Hi,
> 
> we still need the documentation on how to use RA. Please provide that via /docs/.
> 
> Best regards, Heinrich

Not mission-critical, since anybody who cannot make sense of the parameters by reading the commends in the `application.properties` file will also not be able to setup the CMC right now, by any means.
But will provide that as well.

**Comment by milux** [comment]
Hi,

> * The Changelog is missing.

I'm not familiar with your expectations regarding your CHANGELOG, especially granularity etc. Could you please elaborate or include a few lines on your own?

> * The temporary publishing to local repository needs to be removed.

Then maven dependency resolution will break, as maven publishing is blocked right now.
The local repository is a sane workaround for that situation, feel free to remove it as soon as maven central is fixed and we were able to publish a fixed release.

> * The e2e test are failing.

I know, and I do neither have any idea why, nor does your pipeline give any useful hint.
Assume broken test or weird side-effect unless you can tell me what's going wrong.

> * The changes to the dockerfile seem strange. Would you be so kind to explain why a local copy of the configuration is added as a single layer?

IDSCP2 library is resolving the certificate paths in a way that prohibits use of JAR-embedded files. These have to be available in the file system, otherwise resolution will fail.

**Comment by brianjahnke** [comment]
Hi,
- Here the example [Changelog](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/CHANGELOG.md) for reference.
- This "tmp" fix should not be pushed to main.
- The e2e are reporting a timeout. This means usually the container is not even starting. They can be started locally.
- What prohibits the mounting of a volume?

**Comment by milux** [comment]
Hi,

> * Here the example [Changelog](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/CHANGELOG.md) for reference.

I know the README, but judging from past experiences, I assume that we could have another 3 iterations or so about details in the CHANGELOG if I start working here.
You know best what you expect in your CHANGELOG, in what format, to what granularity. The time of both of us would be wisely invested if you stop urging me updating your CHANGELOG and insert the information yourself. The PR implements RA via the OSS CMC, plus a fix for libs using java.util.logging, so that their logs are getting directed to log4j.

> * This "tmp" fix should not be pushed to main.

I believe that this fix could seriously help any developer who cannot push to official repositories, as it definitely helped me doing so with our libraries.
I just checked, maven central publishing is still not usable, so at the moment you can accept this or wait for Sonatype to fix their infra and then remove this, whatever seems more pleasant to you.

> * The e2e are reporting a timeout. This means usually the container is not even starting. They can be started locally.

If the container was not running locally, I would not have marked this PR for review. So... cannot reproduce, I guess?

> * What prohibits the mounting of a volume?

Nothing, mounting a volume is perfectly fine as well, but additionally increases the effort for any user to try out the feature, moving it even further away from a plug and play solution.
If that's not a problem to you, again, feel free to remove that.

**Comment by milux** [comment]
Apparently, just disabling IDSCP2 is sufficient to make `e2e-test` pass.
@ronjaquensel You may want to check this out when you have some minutes for that, I think that merely enabling a feature should not break anything, ideally.

**Comment by milux** [comment]
@HeinrichPet Documentation has been provided, see end of `docs/pages/deployment/configuration.md`.

**Comment by milux** [comment]
@brianjahnke I accidentally uploaded modifications using experimental buildkit features in the Dockerfile with the last commits. To my great surprise, this did not smash anything in your pipeline.
As it significantly speeds up maven builds locally (as it provides a mounted cache for maven during builds), you may want to consider keeping these changes and instruct users to use `DOCKER_BUILDKIT=1` and `COMPOSE_DOCKER_CLI_BUILD=1` env vars.
Again, if you don't like it, feel free to remove it.

**Comment by milux** [comment]
@brianjahnke The local artifacts have now been removed, as the artifacts become available in maven central.
If you think that the local artifact repository doesn't provide any benefit, once again, please feel free to remove that.

I'm done here, I think.

So long, and thanks for all the fish.

**Review by juliapampus — APPROVED** [review]

**Pull request merged**
